name: ${project.name}
main: fr.keke142.worldupdater.WorldUpdaterPlugin
version: ${project.version}
author: keke142
depend:
  - FastAsyncWorldEdit
  - WorldGuard
commands:
  convertmyworld:
    default: op